### Reset Data
POST http://localhost:4004/API_BUSINESS_PARTNER/reset
Content-Type: application/json

{}

### Read Business Partner 
GET http://localhost:4004/API_BUSINESS_PARTNER/A_BusinessPartner

### Read Business Partner V2
GET http://localhost:4004/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_BusinessPartner?$expand=to_Customer,to_Customer/to_CustomerSalesArea
### Read Customer Sales Area V2
GET http://localhost:4004/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_CustomerSalesArea

### Read Business Partner Address
GET http://localhost:4004/API_BUSINESS_PARTNER/A_BusinessPartnerAddress(BusinessPartner='1000021',AddressID='24134')


### Read Business Partner V2
GET https://908489e8trial-dev-customer-material-management-mock-srv.cfapps.us10.hana.ondemand.com/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_BusinessPartner?$expand=to_Customer,to_Customer/to_CustomerSalesArea


### Read Business Partner Mock
GET http://localhost:4004/api-business-partner/A_BusinessPartner
### Read Business Partner Mock OData V2
GET http://localhost:4004/v2/api-business-partner/A_BusinessPartner
### Read Business Partner Mock and Customer OData V2
GET http://localhost:4004/v2/api-business-partner/A_BusinessPartner?$expand=to_Customer


### Read Customer OData V2
GET http://localhost:4004/v2/api-business-partner/A_Customer?$expand=to_CustomerSalesArea