### Read Customer Material
GET http://localhost:3000/API_CUSTOMER_MATERIAL_SRV/A_CustomerMaterial
### Read Customer Material V2
GET http://localhost:3000/sap/opu/odata/sap/API_CUSTOMER_MATERIAL_SRV/A_CustomerMaterial

### Read Single Customer Material V2
GET http://localhost:3000/sap/opu/odata/sap/API_CUSTOMER_MATERIAL_SRV/A_CustomerMaterial%28SalesOrganization%3D%271710%27%2CDistributionChannel%3D%2710%27%2CCustomer%3D%271000021%27%2CMaterial%3D%27TG11%27%29
### Read Customer Material Mock
GET http://localhost:3000/api-customer-material-srv/A_CustomerMaterial
### Read Customer Material Mock OData V2
GET http://localhost:3000/v2/api-customer-material-srv/A_CustomerMaterial